// §07 — the text layer is a provider with a single method. Ship with
// the public-domain text bundled (Path B) so the app ALWAYS works;
// the licensed NIV rides on top via API.Bible (Path A) when a key is
// present, with WEB as the offline floor.

export interface Verse {
  book: string;
  chapter: number;
  verse: number;
  text: string;
  /** True when this verse opens a paragraph — sittings never split mid-thought. */
  paragraphStart?: boolean;
}

export interface TextProvider {
  getChapter(book: string, ch: number): Promise<Verse[]>;
  /** Rendered under every chapter if non-null. For NIV this notice is a licence condition, not a nicety. */
  attribution(): string | null;
}

// ── Bundled (Path B) ─────────────────────────────────────────────
// Slim on-disk shape: books.<id> = chapters[][] of { v, t, p? }.
// Generated by scripts/build-bible.mjs into /assets/bible/web.json.

export interface BundledVerse {
  v: number;
  t: string;
  p?: 1;
}

export interface BundledBible {
  translation: string;
  attribution: string | null;
  books: Record<string, BundledVerse[][]>;
}

export class BundledProvider implements TextProvider {
  constructor(private readonly data: BundledBible) {}

  async getChapter(book: string, ch: number): Promise<Verse[]> {
    const chapters = this.data.books[book];
    const verses = chapters?.[ch - 1];
    if (!verses) throw new Error(`No such chapter: ${book} ${ch}`);
    return verses.map((x) => ({
      book,
      chapter: ch,
      verse: x.v,
      text: x.t,
      ...(x.p ? { paragraphStart: true } : {}),
    }));
  }

  attribution(): string | null {
    return this.data.attribution;
  }

  chapterCount(book: string): number {
    return this.data.books[book]?.length ?? 0;
  }
}

// ── Chained (Path A over Path B) ─────────────────────────────────
// Try providers in order; first success wins. NIV first when a key
// exists, bundled WEB as the floor that cannot fail offline.

export class ChainedProvider implements TextProvider {
  private lastUsed: TextProvider | null = null;

  constructor(private readonly providers: TextProvider[]) {
    if (providers.length === 0) throw new Error('ChainedProvider needs at least one provider');
  }

  async getChapter(book: string, ch: number): Promise<Verse[]> {
    let lastError: unknown;
    for (const p of this.providers) {
      try {
        const verses = await p.getChapter(book, ch);
        this.lastUsed = p;
        return verses;
      } catch (e) {
        lastError = e;
      }
    }
    throw lastError;
  }

  /** Attribution of whichever provider actually served the last chapter. */
  attribution(): string | null {
    return (this.lastUsed ?? this.providers[this.providers.length - 1]).attribution();
  }
}
